### PR TITLE
modify ifc-js extension name

### PR DESCRIPTION
**Pull request by vascoguita**

### CODE REVIEW

**Comment by diocas** [comment]
@vascoguita please change the hardcoded path to the next version so that we merge all together

**Comment by vascoguita** [comment]
> @vascoguita please change the hardcoded path to the next version so that we merge all together

I changed the version on ifs-js/package.json and on the path to the IFC WASM file on ifs-js/src/App.vue.
Is ok now?

**Comment by diocas** [comment]
No, you should not change package.json, that will be automatically updated. And why .3? I saw some .2 appearing but we should remove it since it was not done properly.

**Comment by vascoguita** [comment]
> No, you should not change package.json, that will be automatically updated. And why .3? I saw some .2 appearing but we should remove it since it was not done properly.

Ok, I reverted package.json to how it was before and changed the path to the  IFC WASM file to version .2
Is it OK now?

**Review by diocas — APPROVED** [review]

**Pull request merged**
