### PR TITLE
feat: lightweight account home page

### PR DESCRIPTION
**Pull request by JammingBen**
Adds a landing page for lightweight user accounts, similar as it's done in https://github.com/owncloud/web/commit/9c4ec26e770d914b34a8e16270f51906a9fa09ea. It checks for the user role, which is the indicator for lightweight users in our (owncloud) case: `user.role?.name === 'user-light'`

image

Works towards https://github.com/owncloud/web/issues/9381

### CODE REVIEW

**Comment by diocas** [comment]
Thanks for the PR @JammingBen  (I missed it, sorry for the delay). 

Just a point to confirm: 
- when you login you are redirected to `homeFolder`. But when you are a lightweight account, your `homeFolder` needs to change to the page you contributed. Would this be possible?

**Comment by JammingBen** [comment]
> when you login you are redirected to homeFolder. But when you are a lightweight account, your homeFolder needs to change to the page you contributed. Would this be possible?

What exactly is the page you contributed and how to retrieve it? In general, the nav item can also have a `handler` callback on click that e.g. retrieves the page and then routes to it. Or does it have a fixed path?

**Comment by elizavetaRa** [comment]
In your current latest there is this in response: `
<user-type>
primary
</user-type>`
Why use `user-role` and not `user-type`?

**Comment by dschmidt** [comment]
user-type is not a concept in our product, afaict. So we used something we have.  In your extension you are obviously free to do whatever

**Comment by diocas** [comment]
@dschmidt did not try yet and I missed the code that does that... Sorry, everything should be fine then.

**Review by diocas — APPROVED** [review]

**Pull request merged**
